# Bangladesh Housing & Population Census - Data cleaning

## 1. Setup & Data Loading

In [4]:
import pandas as pd
import numpy as np

In [5]:
df=pd.read_csv("housing_census.csv")

## Standardizing column names

In [6]:
df.columns= (df.columns.str.strip().str.lower().str.replace(r"[^\w\s]","",regex= True).str.replace(r"\s+","_",regex=True))

In [7]:

df.columns = df.columns.str.replace("'", "").str.strip().str.lower()

In [8]:
df.head()

,division,district,division_geocode,district_geocode,household_total,population_total,household_excluding_slum_floating,population_excluding_slum_floating,household_slum,population_slum,...,number_of_person_avg_hh_size__of_hh_with_3person,number_of_person_avg_hh_size__of_hh_with_4person,number_of_person_avg_hh_size__of_hh_with_5person,number_of_person_avg_hh_size__of_hh_with_6person,number_of_person_avg_hh_size__of_hh_with_7person,number_of_person_avg_hh_size__of_hh_with_8person,number_of_person_avg_hh_size__of_hh_with_9person,number_of_person_avg_hh_size__of_hh_with_10person,number_of_person_avg_hh_size__of_hh_with_10person_,number_of_person_avg_hh_size_average_household_size
0,Barishal,Barguna,10,4,255390,1010531,254895,1008695,451,1789,...,57097,68828,43330,20901,8395,3499,1583,772,767,3.92
1,Khulna,Bagerhat,40,1,408840,1613076,406058,1603126,2605,9763,...,96057,109638,68442,32081,12933,5722,2560,1324,1236,3.89
2,Barishal,Barishal,10,6,629626,2570446,620735,2537292,8160,31338,...,135271,165285,110132,54039,23613,10535,5289,2819,2981,4.02
3,Barishal,Bhola,10,9,449057,1932518,448944,1932138,74,339,...,89014,118802,92260,46329,20396,9347,4588,2375,2574,4.27
4,Barishal,Jhalokati,10,42,162401,661160,162212,660520,143,588,...,34540,41357,27852,14052,6339,3084,1529,815,904,4.02

In [9]:
df.tail()

,division,district,division_geocode,district_geocode,household_total,population_total,household_excluding_slum_floating,population_excluding_slum_floating,household_slum,population_slum,...,number_of_person_avg_hh_size__of_hh_with_3person,number_of_person_avg_hh_size__of_hh_with_4person,number_of_person_avg_hh_size__of_hh_with_5person,number_of_person_avg_hh_size__of_hh_with_6person,number_of_person_avg_hh_size__of_hh_with_7person,number_of_person_avg_hh_size__of_hh_with_8person,number_of_person_avg_hh_size__of_hh_with_9person,number_of_person_avg_hh_size__of_hh_with_10person,number_of_person_avg_hh_size__of_hh_with_10person_,number_of_person_avg_hh_size_average_household_size
59,Rangpur,Panchagarh,55,77,281627,1179843,280851,1176974,735,2827,...,56319,81106,53595,26636,11085,4651,2404,1281,1416,4.14
60,Rangpur,Rangpur,55,85,834307,3169614,826692,3141432,7447,28003,...,203689,231968,124275,52856,20364,8494,4142,2101,2248,3.72
61,Rangpur,Thakurgaon,55,94,382400,1533895,381262,1529809,1021,3930,...,82779,112589,66032,30798,11940,4898,2590,1297,1416,3.96
62,Sylhet,Sunamganj,60,90,528550,2695496,527545,2691484,865,3868,...,70460,104937,105541,78260,48226,27163,14596,8854,13911,5.09
63,Sylhet,Sylhet,60,91,746854,3857123,722553,3753617,23853,103032,...,102825,152780,143801,101254,62353,36293,21359,13723,24742,5.13

## Fixing Categorical & identifier data types

In [10]:
df["division_geocode"] = df["division_geocode"].astype(str)
df["district_geocode"] = df["district_geocode"].astype(str)

In [11]:
df.head()

,division,district,division_geocode,district_geocode,household_total,population_total,household_excluding_slum_floating,population_excluding_slum_floating,household_slum,population_slum,...,number_of_person_avg_hh_size__of_hh_with_3person,number_of_person_avg_hh_size__of_hh_with_4person,number_of_person_avg_hh_size__of_hh_with_5person,number_of_person_avg_hh_size__of_hh_with_6person,number_of_person_avg_hh_size__of_hh_with_7person,number_of_person_avg_hh_size__of_hh_with_8person,number_of_person_avg_hh_size__of_hh_with_9person,number_of_person_avg_hh_size__of_hh_with_10person,number_of_person_avg_hh_size__of_hh_with_10person_,number_of_person_avg_hh_size_average_household_size
0,Barishal,Barguna,10,4,255390,1010531,254895,1008695,451,1789,...,57097,68828,43330,20901,8395,3499,1583,772,767,3.92
1,Khulna,Bagerhat,40,1,408840,1613076,406058,1603126,2605,9763,...,96057,109638,68442,32081,12933,5722,2560,1324,1236,3.89
2,Barishal,Barishal,10,6,629626,2570446,620735,2537292,8160,31338,...,135271,165285,110132,54039,23613,10535,5289,2819,2981,4.02
3,Barishal,Bhola,10,9,449057,1932518,448944,1932138,74,339,...,89014,118802,92260,46329,20396,9347,4588,2375,2574,4.27
4,Barishal,Jhalokati,10,42,162401,661160,162212,660520,143,588,...,34540,41357,27852,14052,6339,3084,1529,815,904,4.02

In [12]:
df.describe()

,household_total,population_total,household_excluding_slum_floating,population_excluding_slum_floating,household_slum,population_slum,household_floating,population_floating,population_density,type_of_household_household_total_except_floating_,...,number_of_person_avg_hh_size__of_hh_with_3person,number_of_person_avg_hh_size__of_hh_with_4person,number_of_person_avg_hh_size__of_hh_with_5person,number_of_person_avg_hh_size__of_hh_with_6person,number_of_person_avg_hh_size__of_hh_with_7person,number_of_person_avg_hh_size__of_hh_with_8person,number_of_person_avg_hh_size__of_hh_with_9person,number_of_person_avg_hh_size__of_hh_with_10person,number_of_person_avg_hh_size__of_hh_with_10person_,number_of_person_avg_hh_size_average_household_size
count,6.400000e+01,6.400000e+01,6.400000e+01,6.400000e+01,64.000000,64.000000,64.000000,64.000000,64.000000,6.400000e+01,...,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000
mean,6.407534e+05,2.580603e+06,6.327701e+05,2.553127e+06,7684.296875,27129.718750,298.968750,346.640625,1297.015625,6.404544e+05,...,140580.968750,163438.796875,104034.093750,51471.812500,23050.875000,10938.828125,5659.546875,3156.812500,4164.250000,4.031406
std,5.635301e+05,2.134836e+06,5.382841e+05,2.052937e+06,27837.256493,93746.357796,770.804115,853.589477,1334.758161,5.628492e+05,...,127738.850564,136359.196436,78102.420883,37512.175318,18268.022438,9525.834931,5253.640271,3221.510298,5208.502728,0.355335
min,1.061550e+05,4.811060e+05,1.060650e+05,4.810160e+05,0.000000,0.000000,0.000000,0.000000,106.000000,1.060650e+05,...,19346.000000,24439.000000,19101.000000,11631.000000,4149.000000,1557.000000,688.000000,342.000000,252.000000,3.290000
25%,3.381995e+05,1.395069e+06,3.357908e+05,1.387069e+06,317.750000,1201.500000,69.250000,88.250000,876.750000,3.380628e+05,...,72684.500000,92999.750000,61767.750000,29641.250000,12291.750000,5211.750000,2527.250000,1278.500000,1406.750000,3.805000
50%,5.225860e+05,2.156286e+06,5.212175e+05,2.148722e+06,1461.000000,5622.000000,127.500000,150.000000,1083.500000,5.223940e+05,...,102796.500000,134460.000000,92195.000000,43650.000000,17348.000000,8212.500000,3894.000000,1940.500000,2267.000000,3.985000
75%,7.503785e+05,2.955293e+06,7.452630e+05,2.935862e+06,3130.000000,12305.750000,275.750000,302.250000,1296.000000,7.499612e+05,...,165187.250000,184179.750000,123470.750000,58406.250000,26124.250000,11893.750000,6062.500000,3244.750000,3958.750000,4.150000
max,4.035241e+06,1.473470e+07,3.822371e+06,1.404069e+07,206900.000000,687534.000000,5970.000000,6477.000000,10067.000000,4.029271e+06,...,914430.000000,969773.000000,504971.000000,211944.000000,89097.000000,44943.000000,24934.000000,15625.000000,25295.000000,5.130000

In [13]:
for i, column in enumerate(df.columns, start=1):
    print(f"{i}.{column}")

1.division
2.district
3.division_geocode
4.district_geocode
5.household_total
6.population_total
7.household_excluding_slum_floating
8.population_excluding_slum_floating
9.household_slum
10.population_slum
11.household_floating
12.population_floating
13.population_density
14.type_of_household_household_total_except_floating_
15.type_of_household_population__except_floating_
16.type_of_household_household_general_
17.type_of_household_population_general_
18.type_of_household_household_institutional
19.type_of_household_population_institutional_
20.type_of_household_household_other_
21.type_of_household_population_other_
22.type_of_dwelling_sex_dist_population_total_
23.type_of_dwelling_sex_dist_population_male_
24.type_of_dwelling_sex_dist_population_female_
25.type_of_dwelling_sex_dist_population_hijra_
26.type_of_dwelling_sex_dist_population_excluding_slum_floating_total_
27.type_of_dwelling_sex_dist_population_excluding_slum_floating_male_
28.type_of_dwelling_sex_dist_population_excluding_slum_floating_female_
29.type_of_dwelling_sex_dist_population_excluding_slum_floating_hijra_
30.type_of_dwelling_sex_dist_population_slum_total_
31.type_of_dwelling_sex_dist_population_slum_male_
32.type_of_dwelling_sex_dist_population_slum_female_
33.type_of_dwelling_sex_dist_population_slum_hijra_
34.type_of_dwelling_sex_dist_population_floating_total_
35.type_of_dwelling_sex_dist_population_floating_male_
36.type_of_dwelling_sex_dist_population_floating_female_
37.type_of_dwelling_sex_dist_population_floating_hijra_
38.population_by_sex_dist_loca_population_total_
39.population_by_sex_dist_loca_population_male_
40.population_by_sex_dist_loca_population_female_
41.population_by_sex_dist_loca_population_hijra_
42.population_by_sex_dist_loca_population_rural_total_
43.population_by_sex_dist_loca_population_rural_male_
44.population_by_sex_dist_loca_population_rural_female_
45.population_by_sex_dist_loca_population_rural_hijra_
46.population_by_sex_dist_loca_population_urban_total_
47.population_by_sex_dist_loca_population_urban_male_
48.population_by_sex_dist_loca_population_urban_female_
49.population_by_sex_dist_loca_population_urban_hijra_
50.type_of_household_dist_and_loca__population
51.type_of_household_dist_and_loca__population__general_hh
52.type_of_household_dist_and_loca__population__institutional_hh
53.type_of_household_dist_and_loca__population_other_hh
54.type_of_household_dist_and_loca__population_general_hh
55.type_of_household_dist_and_loca__population_institutional_hh
56.type_of_household_dist_and_loca__population_other_hh
57.type_of_household_loca_rural__population_rural
58.type_of_household_loca_rural__population__general_hh_rural
59.type_of_household_loca_rural__population_institutional_hh_rural
60.type_of_household_loca_rural__population_other_hh_rural
61.type_of_household_loca_rural__population_general_hh_rural
62.type_of_household_loca_rural__population_institutional_hh_rural
63.type_of_household_loca_rural__population_other_hh_rural
64.type_of_household_loca_urban_population_urban
65.type_of_household_loca_urban_population__general_hh_urban
66.type_of_household_loca_urban_population_institutional_hh_urban
67.type_of_household_loca_urban_population_other_hh_urban
68.type_of_household_loca_urban_population_general_hh_urban
69.type_of_household_loca_urban_population_institutional_hh_urban
70.type_of_household_loca_urban_population_other_hh_urban
71.10_yrs_above_by_mar_sta_sex__population
72.10_yrs_above_by_mar_sta_sex__male
73.10_yrs_above_by_mar_sta_sex__female
74.10_yrs_above_by_mar_sta_sex__never_married_population
75.10_yrs_above_by_mar_sta_sex__never_married_population_male
76.10_yrs_above_by_mar_sta_sex__never_married_population_female
77.10_yrs_above_by_mar_sta_sex__currently_married_population
78.10_yrs_above_by_mar_sta_sex__currently_married_population_male
79.10_yrs_above_by_mar_sta_sex__currently_married_population_female
80.10_yrs_above_by_mar_sta_sex__widowwidower_population
81.10_yrs_above_by_mar_sta_sex__widowwidower_population_male
82.10_yrs_above_by_mar_sta_sex__widowwidower_population_female
83.10_yrs_above_by_mar_sta_sex__divorced_population
84.10_yrs_above_by_mar_sta_sex__divorced_population_male
85.10_yrs_above_by_mar_sta_sex__divorced_population_female
86.10_yrs_above_by_mar_sta_sex__separated_population
87.10_yrs_above_by_mar_sta_sex__separated_population_male
88.10_yrs_above_by_mar_sta_sex__separated_population_female
89.population_by_religion_sex__total_muslim
90.population_by_religion_sex__male_muslim
91.population_by_religion_sex__female_muslim
92.population_by_religion_sex__total_hindu
93.population_by_religion_sex__male_hindu
94.population_by_religion_sex__female_hindu
95.population_by_religion_sex__total_christian
96.population_by_religion_sex__male_christian
97.population_by_religion_sex__female_christian
98.population_by_religion_sex__total_buddhist
99.population_by_religion_sex__male_buddhist
100.population_by_religion_sex__female_buddhist
101.population_by_religion_sex__total_others
102.population_by_religion_sex__male_others
103.population_by_religion_sex__female_others
104.population_growth_rate_sex_rat_overall_avg_population_growth
105.population_growth_rate_sex_rat_overall_sex_ratio
106.population_growth_rate_sex_rat_overall_dependeny_ratio
107.population_growth_rate_sex_rat_overall_childwoman_ratio
108.population_growth_rate_sex_rat_rural_avg_population_growth
109.population_growth_rate_sex_rat_rural_sex_ratio
110.population_growth_rate_sex_rat_rural_dependeny_ratio
111.population_growth_rate_sex_rat_rural_childwoman_ratio
112.population_growth_rate_sex_rat_urban_avg__population_growth
113.population_growth_rate_sex_rat_urban_sex_ratio
114.population_growth_rate_sex_rat_urban_dependeny_ratio
115.population_growth_rate_sex_rat_urban_childwoman_ratio
116.person_with_disablity_except_hijra_total_persons_with_disability_
117.person_with_disablity_except_hijra_autism_or_autism_spectrum_disorders_
118.person_with_disablity_except_hijra_physical_disability_
119.person_with_disablity_except_hijra_mental_illness_leading_to_disability_
120.person_with_disablity_except_hijra_visual_disability_
121.person_with_disablity_except_hijra_speech_disability_
122.person_with_disablity_except_hijra_intellectual_disability_
123.person_with_disablity_except_hijra_hearing_disability_
124.person_with_disablity_except_hijra_deaf_blindness_
125.person_with_disablity_except_hijra_cerebral_palsy_
126.person_with_disablity_except_hijra_down_syndrome_
127.person_with_disablity_except_hijra_multiple_disabilities_
128.person_with_disablity_except_hijra_other_disability_
129.literacy_rate_5year_overall
130.literacy_rate_5year_male
131.literacy_rate_5year_female
132.rural_literacy_rate_5year_overall
133.rural_literacy_rate_5year_male
134.rural_literacy_rate_5year_female
135.urban_literacy_rate_5year_overall
136.urban_literacy_rate_5year_male
137.urban_literacy_rate_5year_female
138.literacy_rate_7year_overall
139.literacy_rate_7year_male
140.literacy_rate_7year_female
141.rural_literacy_rate_7year_overall
142.rural_literacy_rate_7year_male
143.rural_literacy_rate_7year_female
144.urban_literacy_rate_7year_overall
145.urban_literacy_rate_7year_male
146.urban_literacy_rate_7year_female
147.literacy_rate_aged_7_yrs_ab_re_muslim
148.literacy_rate_aged_7_yrs_ab_re_hindu
149.literacy_rate_aged_7_yrs_ab_re_christian
150.literacy_rate_aged_7_yrs_ab_re_buddist
151.literacy_rate_aged_7_yrs_ab_re_others
152.literacy_rate_aged_7_yrs_ab_re_muslim_male
153.literacy_rate_aged_7_yrs_ab_re_hindu_male
154.literacy_rate_aged_7_yrs_ab_re_christian_male
155.literacy_rate_aged_7_yrs_ab_re_buddist_male
156.literacy_rate_aged_7_yrs_ab_re_others_male
157.literacy_rate_aged_7_yrs_ab_re_muslim_female
158.literacy_rate_aged_7_yrs_ab_re_hindu_female
159.literacy_rate_aged_7_yrs_ab_re_christian_female
160.literacy_rate_aged_7_yrs_ab_re_buddist_female
161.literacy_rate_aged_7_yrs_ab_re_others_female
162.total_male_student_529_years_
163.total_female_student_529_years_
164.59_year_male_student_
165.59_year_female_student_
166.1014_years_male_student_
167.1014_years_female_student_
168.1519_years_male_student_
169.1519_years_female_student_
170.2024_years_female_student_
171.2024_years_male_student_
172.2529_years_male_student_
173.2529_years_female_student_
174.overall_working_status_5_year_
175.overall_working_status_5_year_male_
176.overall_working_status_5_year_female_
177.overall_employed_working_status_5_year_
178.overall_employed_working_status_5_year_male_
179.overall_employed_working_status_5_year_female_
180.overall_household_work_working_status_5_year_
181.overall_household_work_working_status_5_year_male_
182.overall_household_work_working_status_5_year_female_
183.overall_looking_for_work_working_status_5_year_
184.overall_looking_for_work_working_status_5_year_male_
185.overall_looking_for_work_working_status_5_year_female_
186.overall_do_not_work_working_status_5_year_
187.overall_do_not_work_working_status_5_year_male_
188.overall_do_not_work_working_status_5_year_female_
189.type_of_work_total_employed_population_
190.type_of_work_male_employed_population__
191.type_of_work_female_employed_population_
192.type_of_work_total_salarywage_
193.type_of_work_male_salarywage_
194.type_of_work_female_salarywage_
195.type_of_work_total_profit_
196.type_of_work_male_profit_
197.type_of_work_female_profit_
198.type_of_work_total_household_useconsumption_
199.type_of_work_male_household_useconsumption_
200.type_of_work_female_household_useconsumption_
201.type_of_work_total_apprenticeship_
202.type_of_work_male_apprenticeship_
203.type_of_work_female_apprenticeship_
204.total_employed_population_
205.employed_population_by_sector_male_
206.employed_population_by_sector_female_
207.employed_population_by_sector_total_agriculture_
208.employed_population_by_sector_male_agriculture_
209.employed_population_by_sector_female_agriculture_
210.employed_population_by_sector_total_industry_
211.employed_population_by_sector_male_industry_
212.employed_population_by_sector_female_industry_
213.employed_population_by_sector_total_service_
214.employed_population_by_sector_male_service_
215.employed_population_by_sector_female_service_
216.1524_years_neet__overall
217.1524_years_neet__male_overall
218.1524_years_neet__female_overall
219.1524_years_neet__rural_overall
220.1524_years_neet__male_rural_overall
221.1524_years_neet__female_rural_overall
222.1524_years_neet__urban_overall
223.1524_years_neet__male_urban_overall
224.1524_years_neet__female_urban_overall
225.1524_years_neet__15_19_year_overall
226.1524_years_neet__male_15_19_year
227.1524_years_neet__female_15_19_year
228.1524_years_neet__rural_15_19_year
229.1524_years_neet__male_rural_15_19_year
230.1524_years_neet__female_rural_15_19_year
231.1524_years_neet__urban_15_19_year
232.1524_years_neet__male_urban_15_19_year
233.1524_years_neet__female_urban_15_19_year
234.1524_years_neet__20_24_year_overall
235.1524_years_neet__male_20_24_year
236.1524_years_neet__female_20_24_year
237.1524_years_neet__rural_20_24_year
238.1524_years_neet__male_rural_20_24_year
239.1524_years_neet__female_rural_20_24_year
240.1524_years_neet__urban_20_24_year
241.1524_years_neet__male_urban_20_24_year
242.1524_years_neet__female_urban_20_24_year
243._mobile_phone_total_5year
244._mobile_phone_male_5year
245._mobile_phone_female_5year
246._mobile_phone_rural_total_5year
247._mobile_phone_rural_male_5year
248._mobile_phone_rural_female_5year
249._mobile_phone_urban_total_5year
250._mobile_phone_urban_male_5year
251._mobile_phone_urban_female_5year
252._mobile_phone_total_15_year
253._mobile_phone_male_15_year
254._mobile_phone_female_15_year
255._mobile_phone_rural_total_15_year
256._mobile_phone_rural_male_15_year
257._mobile_phone_rural_female_15_year
258._mobile_phone_urban_total_15_year
259._mobile_phone_urban_male_15_year
260._mobile_phone_urban_female_15_year
261._inernet_total_5year
262._inernet_male_5year
263._inernet_female_5year
264._inernet_rural_total_5year
265._inernet_rural_male_5year
266._inernet_rural_female_5year
267._inernet_urban_total_5year
268._inernet_urban_male_5year
269._inernet_urban_female_5year
270._inernet_total_15_year
271._inernet_male_15_year
272._inernet_female_15_year
273._inernet_rural_total_15_year
274._inernet_rural_male_15_year
275._inernet_rural_female_15_year
276._inernet_urban_total_15_year
277._inernet_urban_male_15_year
278._inernet_urban_female_15_year
279._have_financial_account_overall
280._have_financial_account_male
281._have_financial_account_female
282._have_financial_account_rural
283._have_financial_account_rural_male
284._have_financial_account_rural_female
285._have_financial_account_urban
286._have_financial_account_urban_male
287._have_financial_account_urban_female
288._mobile_bank_account_overall
289._mobile_bank_account_male
290._mobile_bank_account_female
291._mobile_bank_account_rural
292._mobile_bank_account_rural_male
293._mobile_bank_account_rural_female
294._mobile_bank_account_urban
295._mobile_bank_account_urban_male
296._mobile_bank_account_urban_female
297._overall_ethnic_population
298._male__ethnic_population
299._male_ethnic_population
300._female_ethnic_population
301._female_ethnic_population
302._overall_bangladeshi_national
303._overall_bangladeshi_national
304._male_bangladeshi_national
305._male_bangladeshi_national
306._female_bangladeshi_national
307._female_bangladeshi_national
308._hizra_bangladeshi_national
309._hizra_bangladeshi_national
310.number_returned_migrant
311.percent_returned_migrant
312.household_by_type_of_dwelling__of_hh
313.household_by_type_of_dwelling__rural_hh
314.household_by_type_of_dwelling__of_urban_hh
315.household_by_type_of_dwelling__of_hh_excluding_slum_and_floating
316.household_by_type_of_dwelling__of_hh_excluding_slum_and_floating_rural
317.household_by_type_of_dwelling__of_hh_excluding_slum_and_floating_urban
318.household_by_type_of_dwelling__of_slum_hh
319.household_by_type_of_dwelling__of_slum_hh__rural
320.household_by_type_of_dwelling__of_slum_hh__urban
321.household_by_type_of_dwelling__of_floating_hh
322.household_by_type_of_dwelling__of_floating_hh__rural
323.household_by_type_of_dwelling__of_floating_hh__urban
324.type_of_hh__of_hh
325.type_of_hh__rural_hh
326.type_of_hh__of_urban_hh
327.type_of_hh__of_general_hh
328.type_of_hh__of_general_hh_rural
329.type_of_hh__of_general_hh_urban
330.type_of_hh__of_institutional_household
331.type_of_hh__of_institutional_household_rural
332.type_of_hh__of_institutional_household_urban
333.type_of_hh__of_other_household
334.type_of_hh__of_other_household_rural
335.type_of_hh__of_other_household_urban
336.household_by_wall_material_wall_total
337.household_by_wall_material_wall_cementconcretebrickterracotta
338.household_by_wall_material_wall_ceramic_tiles
339.household_by_wall_material_wall_metal_sheetci_sheetcorrugated_iron_she
340.household_by_wall_material_wall_woodbamboomatpalm_treebetal_nut_trun
341.household_by_wall_material_wall_straw_chhangolpatapalm_leafbichalip
342.household_by_wall_material_wall_soil_mud
343.household_by_wall_material_wall_other_materials
344.household_by_wall_material__no_wall
345.household_by_wall_material_cementconcretebrickterracotta_wall_
346.household_by_wall_material_ceramic_tiles_wall_
347.household_by_wall_material_metal_sheetci_sheetcorrugated_iron_sheet_wal
348.household_by_wall_material_woodbamboomatpalm_treebetal_nut_trunk_wall
349.household_by_wall_material_straw_chhangolpatapalm_leafbichalipolythe
350.household_by_wall_material_soil_mud_wall_
351.household_by_wall_material_other_materials__wall_
352.household_by_wall_material_no_wall_
353.household_by_roof_material__roof_total
354.household_by_roof_material__roof_cementconcretetile
355.household_by_roof_material__roof_metal_sheet_ci_sheetcorrugated_iron_s
356.household_by_roof_material__roof_woodbamboobichaligolpata_palm_leafp
357.household_by_roof_material__roof_handmade_tilestile
358.household_by_roof_material__roof_other_materials
359.household_by_roof_material__no_roof
360.household_by_roof_material_cementconcretetile_roof_
361.household_by_roof_material_metal_sheet_ci_sheetcorrugated_iron_sheet_ro
362.household_by_roof_material_woodbamboobichaligolpata_palm_leafpolythen
363.household_by_roof_material_handmade_tilestile_roof_
364.household_by_roof_material_other_materials_roof_
365.household_by_roof_material_no_roof_
366.household_by_floor_material__floor_total
367.household_by_floor_material__floor_cementconcretebrickterracotta
368.household_by_floor_material__floor_tilesmosaic
369.household_by_floor_material__floor_woodbamboomatpalm_treebetel_nut_t
370.household_by_floor_material__floor_soilsandmud
371.household_by_floor_material__floor_other_materials
372.household_by_floor_material_cementconcretebrickterracotta_floor_
373.household_by_floor_material_tilesmosaic_floor_
374.household_by_floor_material_woodbamboomatpalm_treebetel_nut_trunk_flo
375.household_by_floor_material_soilsandmud_floor_
376.household_by_floor_material_other_materials_floor_
377.household_by_structure__total
378.household_by_structure__pucca
379.household_by_structure__semipucca
380.household_by_structure__kancha
381.household_by_structure__jhupri
382.household_by_structure_total_
383.household_by_structure_pucca_
384.household_by_structure_semipucca_
385.household_by_structure_kancha_
386.household_by_structure_jhupri_
387.household_by_ownership_status_own_dwelling_unit_
388.household_by_ownership_status_rented_but_having_own_dwelling_unit_elsewhere_
389.household_by_ownership_status_rented_and_having_no_own_dwelling_unit_
390.household_by_ownership_status_rent_free_but_having_own_dwelling_unit_elsewhere_
391.household_by_ownership_status_rent_free_and_having_no_own_dwelling_unit_elsewhere_
392.main_source_of_drinking_water_tappipe_supply_
393.main_source_of_drinking_water_tubewell_deepshallow_
394.main_source_of_drinking_water_bottledjar_water_
395.main_source_of_drinking_water_well_
396.main_source_of_drinking_water_pondrivercanallake_
397.main_source_of_drinking_water_spring_
398.main_source_of_drinking_water_rain_water_
399.main_source_of_drinking_water_others_
400.toilet_facilities_safe_disposal_with_flushing_pouring_water_
401.toilet_facilities_safe_disposal_with_flushing_pouring_water_2
402.toilet_facilities_safe_disposal_with_flushing_pouring_water_3
403.toilet_facilities_pit_latrine_without_slab_open__pit
404.toilet_facilities_rawopen_hanging_latrine_permanent_temporary_
405.toilet_facilities_open_defecation_no_latrine_available_
406.type_of_toilet_use_toilet_nottoilet_shared_
407.type_of_toilet_use_toilet_shared_
408.type_of_toilet_use_rural_toilet_nottoilet_shared_
409.type_of_toilet_use_rural_toilet_shared_
410.type_of_toilet_use_urban_toilet_nottoilet_shared_
411.type_of_toilet_use_urban_toilet_shared_
412.handwashing_facilities_soap_water_
413.handwashing_facilities_only_soap_
414.handwashing_facilities_only_water_
415.handwashing_facilities_no_separate_arrangement_
416.main_source_of_electricity_national_grid_
417.main_source_of_electricity_solar_power_
418.main_source_of_electricity_others_
419.main_source_of_electricity_no_electricity_connection_
420.main_source_of_cooking_fuel_straw_leaf_bran_husk_
421.main_source_of_cooking_fuel_wood_chalk_chopped_wood_
422.main_source_of_cooking_fuel_woodcoal_charcoal_dried_dung_
423.main_source_of_cooking_fuel_kerosene_paraffin_
424.main_source_of_cooking_fuel_petrol_diesel_
425.main_source_of_cooking_fuel_electricty_
426.main_source_of_cooking_fuel_supply_gas_
427.main_source_of_cooking_fuel__lp_gas_
428.main_source_of_cooking_fuel_biogas_
429.main_source_of_cooking_fuel_others_
430.foreign_remittance_recipient_total_hh_
431.foreign_remittance_recipient_rural_hh_
432.foreign_remittance_recipient_urban_hh_
433.number_of_person_avg_hh_size_total_hh_
434.number_of_person_avg_hh_size__of_hh_with_1person
435.number_of_person_avg_hh_size__of_hh_with_2person
436.number_of_person_avg_hh_size__of_hh_with_3person

## Replacing literal 's' (or similar typos) with NaN

In [14]:

df = df.replace(['s', 'S', ' ', ''], np.nan)

## Updated Dataframe

In [15]:
df_clean=df.copy()


housing_census_clean=df_clean.to_csv("housing_census_cleaned.csv", index=False)

In [16]:
df_clean.head()

,division,district,division_geocode,district_geocode,household_total,population_total,household_excluding_slum_floating,population_excluding_slum_floating,household_slum,population_slum,...,number_of_person_avg_hh_size__of_hh_with_3person,number_of_person_avg_hh_size__of_hh_with_4person,number_of_person_avg_hh_size__of_hh_with_5person,number_of_person_avg_hh_size__of_hh_with_6person,number_of_person_avg_hh_size__of_hh_with_7person,number_of_person_avg_hh_size__of_hh_with_8person,number_of_person_avg_hh_size__of_hh_with_9person,number_of_person_avg_hh_size__of_hh_with_10person,number_of_person_avg_hh_size__of_hh_with_10person_,number_of_person_avg_hh_size_average_household_size
0,Barishal,Barguna,10,4,255390,1010531,254895,1008695,451,1789,...,57097,68828,43330,20901,8395,3499,1583,772,767,3.92
1,Khulna,Bagerhat,40,1,408840,1613076,406058,1603126,2605,9763,...,96057,109638,68442,32081,12933,5722,2560,1324,1236,3.89
2,Barishal,Barishal,10,6,629626,2570446,620735,2537292,8160,31338,...,135271,165285,110132,54039,23613,10535,5289,2819,2981,4.02
3,Barishal,Bhola,10,9,449057,1932518,448944,1932138,74,339,...,89014,118802,92260,46329,20396,9347,4588,2375,2574,4.27
4,Barishal,Jhalokati,10,42,162401,661160,162212,660520,143,588,...,34540,41357,27852,14052,6339,3084,1529,815,904,4.02

## Verifying total population number for all district.

In [17]:

total_col = "type_of_dwelling_sex_dist_population_total_"
male_col = "type_of_dwelling_sex_dist_population_male_"
female_col = "type_of_dwelling_sex_dist_population_female_"
hijra_col = "type_of_dwelling_sex_dist_population_hijra_"


male_series = pd.to_numeric(df_clean[male_col], errors="coerce").fillna(0)
female_series = pd.to_numeric(df_clean[female_col], errors="coerce").fillna(0)
hijra_series = pd.to_numeric(df_clean[hijra_col], errors="coerce").fillna(0)
total_series = pd.to_numeric(df_clean[total_col], errors="coerce")


calculated = male_series + female_series + hijra_series


print(np.isclose(total_series, calculated, equal_nan=True).all())

True