# Bangladesh Housing & Population Census - Exploratory Data Analysis


## 1. Setup & Data Loading

In [1]:
import pandas as pd

import numpy as np


df=pd.read_csv("housing_census.csv")

## Checking for missing values in columns and the entire dataset.

In [2]:
print("Missing Values in each column:")

print(df.isnull().sum())

Missing Values in each column:
Division                                                   0
District                                                   0
Division_Geocode                                           0
District_Geocode                                           0
Household_Total                                            0
                                                          ..
Number of Person & Avg HH Size_# of HH with 8-Person       0
Number of Person & Avg HH Size_# of HH with 9-Person       0
Number of Person & Avg HH Size_# of HH with 10-Person      0
Number of Person & Avg HH Size_# of HH with 10-Person +    0
Number of Person & Avg HH Size_Average Household Size      0
Length: 445, dtype: int64

 There are not any column with missing values.

## Checking Duplicate rows

In [3]:
print("Number of duplicate rows:",df.duplicated().sum())

Number of duplicate rows: 0

## Printing out the  Column names

In [4]:
for i, column in enumerate(df.columns, start=1):
    print(f"{i}.{column}")

1.Division
2.District
3.Division_Geocode
4.District_Geocode
5.Household_Total
6.Population_Total
7.Household_Excluding_Slum_Floating
8.Population_Excluding_Slum_Floating
9.Household_Slum
10.Population_Slum
11.Household_Floating
12.Population_Floating
13.Population Density
14.Type of Household_Household_total_except_floating_#
15.Type of Household_Population__except_floating_#
16.Type of Household_Household_General_#
17.Type of Household_Population_General_#
18.Type of Household_Household_Institutional
19.Type of Household_Population_Institutional_#
20.Type of Household_Household_Other_#
21.Type of Household_Population_Other_#
22.Type of Dwelling, Sex & Dist_Population_Total_#
23.Type of Dwelling, Sex & Dist_Population_Male_#
24.Type of Dwelling, Sex & Dist_Population_Female_#
25.Type of Dwelling, Sex & Dist_Population_Hijra_#
26.Type of Dwelling, Sex & Dist_Population_Excluding_Slum_Floating_Total_#
27.Type of Dwelling, Sex & Dist_Population_Excluding_Slum_Floating_Male_#
28.Type of Dwelling, Sex & Dist_Population_Excluding_Slum_Floating_Female_#
29.Type of Dwelling, Sex & Dist_Population_Excluding_Slum_Floating_Hijra_#
30.Type of Dwelling, Sex & Dist_Population_Slum_Total_#
31.Type of Dwelling, Sex & Dist_Population_Slum_Male_#
32.Type of Dwelling, Sex & Dist_Population_Slum_Female_#
33.Type of Dwelling, Sex & Dist_Population_Slum_Hijra_#
34.Type of Dwelling, Sex & Dist_Population_Floating_Total_#
35.Type of Dwelling, Sex & Dist_Population_Floating_Male_#
36.Type of Dwelling, Sex & Dist_Population_Floating_Female_#
37.Type of Dwelling, Sex & Dist_Population_Floating_Hijra_#
38.Population by Sex, Dist & Loca_Population_Total_#
39.Population by Sex, Dist & Loca_Population_Male_#
40.Population by Sex, Dist & Loca_Population_Female_#
41.Population by Sex, Dist & Loca_Population_Hijra_#
42.Population by Sex, Dist & Loca_Population_rural_Total_#
43.Population by Sex, Dist & Loca_Population_rural_Male_#
44.Population by Sex, Dist & Loca_Population_rural_Female_#
45.Population by Sex, Dist & Loca_Population_rural_Hijra_#
46.Population by Sex, Dist & Loca_Population_Urban_Total_#
47.Population by Sex, Dist & Loca_Population_Urban_Male_#
48.Population by Sex, Dist & Loca_Population_Urban_Female_#
49.Population by Sex, Dist & Loca_Population_Urban_Hijra_#
50.Type of Household, Dist and Loca_# Population
51.Type of Household, Dist and Loca_# Population_ General HH
52.Type of Household, Dist and Loca_# Population_ Institutional HH
53.Type of Household, Dist and Loca_# Population_other HH
54.Type of Household, Dist and Loca_% Population_General HH
55.Type of Household, Dist and Loca_% Population_Institutional HH
56.Type of Household, Dist and Loca_% Population_other HH
57.Type of Household, Loca_Rural_# Population_Rural
58.Type of Household, Loca_Rural_# Population_ General HH_Rural
59.Type of Household, Loca_Rural_# Population_Institutional HH_Rural
60.Type of Household, Loca_Rural_# Population_other HH_Rural
61.Type of Household, Loca_Rural_% Population_General HH_Rural
62.Type of Household, Loca_Rural_% Population_Institutional HH_Rural
63.Type of Household, Loca_Rural_% Population_other HH_Rural
64.Type of Household, Loca_Urban.# Population_Urban
65.Type of Household, Loca_Urban.# Population_ General HH_Urban
66.Type of Household, Loca_Urban.# Population_Institutional HH_Urban
67.Type of Household, Loca_Urban.# Population_other HH_Urban
68.Type of Household, Loca_Urban.% Population_General HH_Urban
69.Type of Household, Loca_Urban.% Population_Institutional HH_Urban
70.Type of Household, Loca_Urban.% Population_other HH_Urban
71.10 Yrs & above by Mar Sta_Sex_# population
72.10 Yrs & above by Mar Sta_Sex_# Male
73.10 Yrs & above by Mar Sta_Sex_# female
74.10 Yrs & above by Mar Sta_Sex_# Never married population
75.10 Yrs & above by Mar Sta_Sex_# Never married population_male
76.10 Yrs & above by Mar Sta_Sex_# Never married population_female
77.10 Yrs & above by Mar Sta_Sex_# Currently married population
78.10 Yrs & above by Mar Sta_Sex_# Currently married population_male
79.10 Yrs & above by Mar Sta_Sex_# Currently married population_female
80.10 Yrs & above by Mar Sta_Sex_# Widow/Widower population
81.10 Yrs & above by Mar Sta_Sex_# Widow/Widower population_male
82.10 Yrs & above by Mar Sta_Sex_# Widow/Widower population_female
83.10 Yrs & above by Mar Sta_Sex_# Divorced population
84.10 Yrs & above by Mar Sta_Sex_# Divorced population_male
85.10 Yrs & above by Mar Sta_Sex_# Divorced population_female
86.10 Yrs & above by Mar Sta_Sex_# Separated population
87.10 Yrs & above by Mar Sta_Sex_# Separated population_male
88.10 Yrs & above by Mar Sta_Sex_# Separated population_female
89.Population by Religion, Sex_# Total_Muslim
90.Population by Religion, Sex_# Male_Muslim
91.Population by Religion, Sex_# Female_Muslim
92.Population by Religion, Sex_# Total_Hindu
93.Population by Religion, Sex_# Male_Hindu
94.Population by Religion, Sex_# Female_Hindu
95.Population by Religion, Sex_# Total_Christian
96.Population by Religion, Sex_# Male_Christian
97.Population by Religion, Sex_# Female_Christian
98.Population by Religion, Sex_# Total_Buddhist
99.Population by Religion, Sex_# Male_Buddhist
100.Population by Religion, Sex_# Female_Buddhist
101.Population by Religion, Sex_# Total_Others
102.Population by Religion, Sex_# Male_Others
103.Population by Religion, Sex_# Female_Others
104.Population Growth Rate, Sex Rat_Overall_Avg_Population Growth
105.Population Growth Rate, Sex Rat_Overall_Sex_Ratio
106.Population Growth Rate, Sex Rat_Overall_Dependeny_Ratio
107.Population Growth Rate, Sex Rat_Overall_Child-Woman Ratio
108.Population Growth Rate, Sex Rat_Rural_Avg. Population Growth
109.Population Growth Rate, Sex Rat_Rural_Sex_Ratio
110.Population Growth Rate, Sex Rat_Rural_Dependeny_Ratio
111.Population Growth Rate, Sex Rat_Rural_Child-Woman Ratio
112.Population Growth Rate, Sex Rat_Urban_Avg__Population Growth
113.Population Growth Rate, Sex Rat_Urban_Sex_Ratio
114.Population Growth Rate, Sex Rat_Urban_Dependeny_Ratio
115.Population Growth Rate, Sex Rat_Urban_Child-Woman Ratio
116.Person With Disablity (Except Hijra)_Total_Persons_With_Disability_#
117.Person With Disablity (Except Hijra)_Autism or Autism Spectrum Disorders_#
118.Person With Disablity (Except Hijra)_Physical Disability_#
119.Person With Disablity (Except Hijra)_Mental Illness Leading to Disability_#
120.Person With Disablity (Except Hijra)_Visual Disability_#
121.Person With Disablity (Except Hijra)_Speech Disability_#
122.Person With Disablity (Except Hijra)_Intellectual Disability_#
123.Person With Disablity (Except Hijra)_Hearing Disability_#
124.Person With Disablity (Except Hijra)_Deaf- Blindness_#
125.Person With Disablity (Except Hijra)_Cerebral Palsy_#
126.Person With Disablity (Except Hijra)_Down Syndrome_#
127.Person With Disablity (Except Hijra)_Multiple Disabilities_#
128.Person With Disablity (Except Hijra)_Other Disability_#
129.Literacy Rate_5year+_Overall
130.Literacy Rate_5year+_Male
131.Literacy Rate_5year+_Female
132.Rural_Literacy Rate_5year+_Overall
133.Rural_Literacy Rate_5year+_Male
134.Rural_Literacy Rate_5year+_Female
135.Urban_Literacy Rate_5year+_Overall
136.Urban_Literacy Rate_5year+_Male
137.Urban_Literacy Rate_5year+_Female
138.Literacy Rate_7year+_Overall
139.Literacy Rate_7year+_Male
140.Literacy Rate_7year+_Female
141.Rural_Literacy Rate_7year+_Overall
142.Rural_Literacy Rate_7year+_Male
143.Rural_Literacy Rate_7year+_Female
144.Urban_Literacy Rate_7year+_Overall
145.Urban_Literacy Rate_7year+_Male
146.Urban_Literacy Rate_7year+_Female
147.Literacy Rate_Aged 7 Yrs Ab_Re_Muslim
148.Literacy Rate_Aged 7 Yrs Ab_Re_Hindu
149.Literacy Rate_Aged 7 Yrs Ab_Re_Christian
150.Literacy Rate_Aged 7 Yrs Ab_Re_Buddist
151.Literacy Rate_Aged 7 Yrs Ab_Re_others
152.Literacy Rate_Aged 7 Yrs Ab_Re_Muslim_Male
153.Literacy Rate_Aged 7 Yrs Ab_Re_Hindu_Male
154.Literacy Rate_Aged 7 Yrs Ab_Re_Christian_Male
155.Literacy Rate_Aged 7 Yrs Ab_Re_Buddist_Male
156.Literacy Rate_Aged 7 Yrs Ab_Re_others_Male
157.Literacy Rate_Aged 7 Yrs Ab_Re_Muslim_Female
158.Literacy Rate_Aged 7 Yrs Ab_Re_Hindu_Female
159.Literacy Rate_Aged 7 Yrs Ab_Re_Christian_Female
160.Literacy Rate_Aged 7 Yrs Ab_Re_Buddist_Female
161.Literacy Rate_Aged 7 Yrs Ab_Re_others_Female
162.Total_Male_Student_5-29 years_#
163.Total_Female_Student_5-29 years_#
164.5-9 Year_Male_Student_#
165.5-9 Year_Female_Student_#
166.10-14 Years_Male_Student_#
167.10-14 Years_Female_Student_#
168.15-19 Years_Male_Student_#
169.15-19 Years_Female_Student_#
170.20-24 Years_Female_Student_#
171.20-24 Years_Male_Student_#
172.25-29 Years_Male_Student_#
173.25-29 Years_Female_Student_#
174.Overall_Working_Status_5 Year+_#
175.Overall_Working_Status_5 Year+_Male_#
176.Overall_Working_Status_5 Year+_Female_#
177.Overall_Employed_Working_Status_5 Year+_#
178.Overall_Employed_Working_Status_5 Year+_Male_#
179.Overall_Employed_Working_Status_5 Year+_Female_#
180.Overall_Household Work_Working_Status_5 Year+_#
181.Overall_Household Work_Working_Status_5 Year+_Male_#
182.Overall_Household Work_Working_Status_5 Year+_Female_#
183.Overall_Looking for work_Working_Status_5 Year+_#
184.Overall_Looking for work_Working_Status_5 Year+_Male_#
185.Overall_Looking for work_Working_Status_5 Year+_Female_#
186.Overall_Do not Work_Working_Status_5 Year+_#
187.Overall_Do not Work_Working_Status_5 Year+_Male_#
188.Overall_Do not Work_Working_Status_5 Year+_Female_#
189.Type of Work_Total_Employed_Population_#
190.Type of Work_Male_Employed_Population _#
191.Type of Work_Female_Employed_Population_#
192.Type of Work_Total_Salary/Wage_#
193.Type of Work_Male_Salary/Wage_#
194.Type of Work_Female_Salary/Wage_#
195.Type of Work_Total_Profit_#
196.Type of Work_Male_Profit_#
197.Type of Work_Female_Profit_#
198.Type of Work_Total_Household Use/Consumption_#
199.Type of Work_Male_Household Use/Consumption_#
200.Type of Work_Female_Household Use/Consumption_#
201.Type of Work_Total_Apprenticeship_#
202.Type of Work_Male_Apprenticeship_#
203.Type of Work_Female_Apprenticeship_#
204.Total_Employed_Population_#
205.Employed Population by Sector_Male_#
206.Employed Population by Sector_Female_#
207.Employed Population by Sector_Total_Agriculture_#
208.Employed Population by Sector_Male_Agriculture_#
209.Employed Population by Sector_Female_Agriculture_#
210.Employed Population by Sector_Total_Industry_#
211.Employed Population by Sector_Male_Industry_#
212.Employed Population by Sector_Female_Industry_#
213.Employed Population by Sector_Total_Service_#
214.Employed Population by Sector_Male_Service_#
215.Employed Population by Sector_Female_Service_#
216.15-24 Years NEET_%_Overall
217.15-24 Years NEET_%_male_Overall
218.15-24 Years NEET_%_female_Overall
219.15-24 Years NEET_%_rural_Overall
220.15-24 Years NEET_%_male_rural_Overall
221.15-24 Years NEET_%_female_rural_Overall
222.15-24 Years NEET_%_urban_Overall
223.15-24 Years NEET_%_male_urban_Overall
224.15-24 Years NEET_%_female_urban_Overall
225.15-24 Years NEET_%_15_19 year_overall
226.15-24 Years NEET_%_male_15_19 year
227.15-24 Years NEET_%_female_15_19 year
228.15-24 Years NEET_%_rural_15_19 year
229.15-24 Years NEET_%_male_rural_15_19 year
230.15-24 Years NEET_%_female_rural_15_19 year
231.15-24 Years NEET_%_urban_15_19 year
232.15-24 Years NEET_%_male_urban_15_19 year
233.15-24 Years NEET_%_female_urban_15_19 year
234.15-24 Years NEET_%_20_24 year_overall
235.15-24 Years NEET_%_male_20_24 year
236.15-24 Years NEET_%_female_20_24 year
237.15-24 Years NEET_%_rural_20_24 year
238.15-24 Years NEET_%_male_rural_20_24 year
239.15-24 Years NEET_%_female_rural_20_24 year
240.15-24 Years NEET_%_urban_20_24 year
241.15-24 Years NEET_%_male_urban_20_24 year
242.15-24 Years NEET_%_female_urban_20_24 year
243.%_Mobile Phone_Total_5year+
244.%_Mobile Phone_Male_5year+
245.%_Mobile Phone_Female_5year+
246.%_Mobile Phone_Rural_Total_5year+
247.%_Mobile Phone_Rural_Male_5year+
248.%_Mobile Phone_Rural_female_5year+
249.%_Mobile Phone_urban_Total_5year+
250.%_Mobile Phone_urban_Male_5year+
251.%_Mobile Phone_urban_female_5year+
252.%_Mobile Phone_Total_15 year+
253.%_Mobile Phone_Male_15 year+
254.%_Mobile Phone_Female_15 year+
255.%_Mobile Phone_Rural_Total_15 year+
256.%_Mobile Phone_Rural_Male_15 year+
257.%_Mobile Phone_Rural_female_15 year+
258.%_Mobile Phone_urban_Total_15 year+
259.%_Mobile Phone_urban_Male_15 year+
260.%_Mobile Phone_urban_female_15 year+
261.%_Inernet_Total_5year+
262.%_Inernet_Male_5year+
263.%_Inernet_Female_5year+
264.%_Inernet_Rural_Total_5year+
265.%_Inernet_Rural_Male_5year+
266.%_Inernet_Rural_female_5year+
267.%_Inernet_urban_Total_5year+
268.%_Inernet_urban_Male_5year+
269.%_Inernet_urban_female_5year+
270.%_Inernet_Total_15 year+
271.%_Inernet_Male_15 year+
272.%_Inernet_Female_15 year+
273.%_Inernet_Rural_Total_15 year+
274.%_Inernet_Rural_Male_15 year+
275.%_Inernet_Rural_female_15 year+
276.%_Inernet_urban_Total_15 year+
277.%_Inernet_urban_Male_15 year+
278.%_Inernet_urban_female_15 year+
279.%_Have financial account_Overall
280.%_Have financial account_Male
281.%_Have financial account_Female
282.%_Have financial account_Rural
283.%_Have financial account_Rural_Male
284.%_Have financial account_Rural_Female
285.%_Have financial account_Urban
286.%_Have financial account_Urban_Male
287.%_Have financial account_Urban_Female
288.%_Mobile Bank Account_Overall
289.%_Mobile Bank Account_Male
290.%_Mobile Bank Account_Female
291.%_Mobile Bank Account_Rural
292.%_Mobile Bank Account_Rural_Male
293.%_Mobile Bank Account_Rural_Female
294.%_Mobile Bank Account_Urban
295.%_Mobile Bank Account_Urban_Male
296.%_Mobile Bank Account_Urban_Female
297.# Overall_Ethnic Population
298.# Male _Ethnic Population
299.% Male_Ethnic Population
300.# Female_Ethnic Population
301.% Female_Ethnic Population
302.# Overall_Bangladeshi_National
303.% Overall_Bangladeshi_National
304.# Male_Bangladeshi_National
305.% Male_Bangladeshi_National
306.# Female_Bangladeshi_National
307.% Female_Bangladeshi_National
308.# Hizra_Bangladeshi_National
309.% Hizra_Bangladeshi_National
310.Number_Returned_Migrant
311.Percent_Returned_Migrant
312.Household by Type of Dwelling_# of HH
313.Household by Type of Dwelling_# Rural HH
314.Household by Type of Dwelling_# of Urban HH
315.Household by Type of Dwelling_# of HH excluding slum and floating
316.Household by Type of Dwelling_# of HH excluding slum and floating_rural
317.Household by Type of Dwelling_# of HH excluding slum and floating_urban
318.Household by Type of Dwelling_# of Slum HH
319.Household by Type of Dwelling_# of Slum HH _rural
320.Household by Type of Dwelling_# of Slum HH _urban
321.Household by Type of Dwelling_# of Floating  HH
322.Household by Type of Dwelling_# of Floating  HH _rural
323.Household by Type of Dwelling_# of Floating HH _urban
324.type of HH_# of HH
325.type of HH_# Rural HH
326.type of HH_# of Urban HH
327.type of HH_# of General HH
328.type of HH_# of General HH_Rural
329.type of HH_# of General HH_Urban
330.type of HH_# of Institutional Household
331.type of HH_# of Institutional Household_Rural
332.type of HH_# of Institutional Household_Urban
333.type of HH_# of Other Household
334.type of HH_# of Other Household_Rural
335.type of HH_# of Other Household_Urban
336.Household by Wall Material_#Wall_Total
337.Household by Wall Material_#Wall_Cement/Concrete/Brick/Terracotta
338.Household by Wall Material_#Wall_Ceramic Tiles
339.Household by Wall Material_#Wall_Metal sheet/CI sheet/Corrugated Iron she
340.Household by Wall Material_#Wall_Wood/Bamboo/Mat/Palm Tree/Betal Nut Trun
341.Household by Wall Material_#Wall_Straw/ Chhan/Golpata/Palm Leaf/Bichali/P
342.Household by Wall Material_#Wall_Soil/ Mud
343.Household by Wall Material_#Wall_Other Materials
344.Household by Wall Material_# No Wall
345.Household by Wall Material_Cement/Concrete/Brick/Terracotta_Wall_%
346.Household by Wall Material_Ceramic Tiles_Wall_%
347.Household by Wall Material_Metal sheet/CI sheet/Corrugated Iron sheet_Wal
348.Household by Wall Material_Wood/Bamboo/Mat/Palm Tree/Betal Nut Trunk_Wall
349.Household by Wall Material_Straw/ Chhan/Golpata/Palm Leaf/Bichali/Polythe
350.Household by Wall Material_Soil/ Mud_Wall_%
351.Household by Wall Material_Other Materials__Wall_%
352.Household by Wall Material_No wall %
353.Household by Roof Material_# roof_Total
354.Household by Roof Material_# roof_Cement/Concrete/Tile
355.Household by Roof Material_# roof_Metal Sheet/ CI Sheet/Corrugated Iron S
356.Household by Roof Material_# roof_Wood/Bamboo/Bichali/Golpata Palm Leaf/P
357.Household by Roof Material_# roof_Hand-made Tiles/Tile
358.Household by Roof Material_# roof_Other Materials
359.Household by Roof Material_# No Roof
360.Household by Roof Material_Cement/Concrete/Tile_roof_%
361.Household by Roof Material_Metal Sheet/ CI Sheet/Corrugated Iron Sheet_ro
362.Household by Roof Material_Wood/Bamboo/Bichali/Golpata Palm Leaf/Polythen
363.Household by Roof Material_Hand-made Tiles/Tile_roof_%
364.Household by Roof Material_Other Materials_roof_%
365.Household by Roof Material_No_roof_%
366.Household by Floor Material_# floor_Total
367.Household by Floor Material_# floor_Cement/Concrete/Brick/Terracotta
368.Household by Floor Material_# floor_Tiles/Mosaic
369.Household by Floor Material_# floor_Wood/Bamboo/Mat/Palm Tree/Betel Nut T
370.Household by Floor Material_# floor_Soil/Sand/Mud
371.Household by Floor Material_# floor_Other Materials
372.Household by Floor Material_Cement/Concrete/Brick/Terracotta_floor_%
373.Household by Floor Material_Tiles/Mosaic_floor_%
374.Household by Floor Material_Wood/Bamboo/Mat/Palm Tree/Betel Nut Trunk_flo
375.Household by Floor Material_Soil/Sand/Mud_floor_%
376.Household by Floor Material_Other Materials_floor_%
377.Household by Structure_#_Total
378.Household by Structure_#_Pucca
379.Household by Structure_#_Semi-pucca
380.Household by Structure_#_Kancha
381.Household by Structure_#_Jhupri
382.Household by Structure_Total_%
383.Household by Structure_Pucca_%
384.Household by Structure_Semi-pucca_%
385.Household by Structure_Kancha_%
386.Household by Structure_Jhupri_%
387.Household by Ownership Status_Own dwelling unit_%
388.Household by Ownership Status_Rented but having own dwelling unit elsewhere_%
389.Household by Ownership Status_Rented and having no own dwelling unit_%
390.Household by Ownership Status_Rent free but having own dwelling unit elsewhere_%
391.Household by Ownership Status_Rent free and having no own dwelling unit elsewhere_%
392.Main Source of Drinking Water_Tap/pipe (Supply)_%
393.Main Source of Drinking Water_Tube-well (Deep/Shallow)_%
394.Main Source of Drinking Water_Bottled/Jar Water_%
395.Main Source of Drinking Water_Well_%
396.Main Source of Drinking Water_Pond/River/Canal/Lake_%
397.Main Source of Drinking Water_Spring_%
398.Main Source of Drinking Water_Rain Water_%
399.Main Source of Drinking Water_Others_%
400.Toilet Facilities_Safe Disposal with Flushing/ Pouring Water_%
401.Toilet Facilities_Safe Disposal with Flushing/ Pouring Water_%2
402.Toilet Facilities_Safe Disposal with Flushing/ Pouring Water_%3
403.Toilet Facilities_Pit Latrine
Without
Slab/ Open_%
Pit
404.Toilet Facilities_Raw/Open/ Hanging Latrine (Permanent/ Temporary)_%
405.Toilet Facilities_Open Defecation/ No Latrine Available_%
406.Type of Toilet Use_Toilet_Not-Toilet_Shared_%
407.Type of Toilet Use_Toilet_Shared_%
408.Type of Toilet Use_Rural_Toilet_Not-Toilet_Shared_%
409.Type of Toilet Use_Rural_Toilet_Shared_%
410.Type of Toilet Use_urban_Toilet_Not-Toilet_Shared_%
411.Type of Toilet Use_urban_Toilet_Shared_%
412.Handwashing Facilities_Soap & Water_%
413.Handwashing Facilities_Only Soap_%
414.Handwashing Facilities_Only Water_%
415.Handwashing Facilities_No Separate Arrangement_%
416.Main Source of Electricity_National Grid_%
417.Main Source of Electricity_Solar Power_%
418.Main Source of Electricity_Others_%
419.Main Source of Electricity_No Electricity Connection_%

## Some features of the dataset

In [5]:
df.head(5)

,Division,District,Division_Geocode,District_Geocode,Household_Total,Population_Total,Household_Excluding_Slum_Floating,Population_Excluding_Slum_Floating,Household_Slum,Population_Slum,...,Number of Person & Avg HH Size_# of HH with 3-Person,Number of Person & Avg HH Size_# of HH with 4-Person,Number of Person & Avg HH Size_# of HH with 5-Person,Number of Person & Avg HH Size_# of HH with 6-Person,Number of Person & Avg HH Size_# of HH with 7-Person,Number of Person & Avg HH Size_# of HH with 8-Person,Number of Person & Avg HH Size_# of HH with 9-Person,Number of Person & Avg HH Size_# of HH with 10-Person,Number of Person & Avg HH Size_# of HH with 10-Person +,Number of Person & Avg HH Size_Average Household Size
0,Barishal,Barguna,10,4,255390,1010531,254895,1008695,451,1789,...,57097,68828,43330,20901,8395,3499,1583,772,767,3.92
1,Khulna,Bagerhat,40,1,408840,1613076,406058,1603126,2605,9763,...,96057,109638,68442,32081,12933,5722,2560,1324,1236,3.89
2,Barishal,Barishal,10,6,629626,2570446,620735,2537292,8160,31338,...,135271,165285,110132,54039,23613,10535,5289,2819,2981,4.02
3,Barishal,Bhola,10,9,449057,1932518,448944,1932138,74,339,...,89014,118802,92260,46329,20396,9347,4588,2375,2574,4.27
4,Barishal,Jhalokati,10,42,162401,661160,162212,660520,143,588,...,34540,41357,27852,14052,6339,3084,1529,815,904,4.02

In [6]:
df.tail(5)

,Division,District,Division_Geocode,District_Geocode,Household_Total,Population_Total,Household_Excluding_Slum_Floating,Population_Excluding_Slum_Floating,Household_Slum,Population_Slum,...,Number of Person & Avg HH Size_# of HH with 3-Person,Number of Person & Avg HH Size_# of HH with 4-Person,Number of Person & Avg HH Size_# of HH with 5-Person,Number of Person & Avg HH Size_# of HH with 6-Person,Number of Person & Avg HH Size_# of HH with 7-Person,Number of Person & Avg HH Size_# of HH with 8-Person,Number of Person & Avg HH Size_# of HH with 9-Person,Number of Person & Avg HH Size_# of HH with 10-Person,Number of Person & Avg HH Size_# of HH with 10-Person +,Number of Person & Avg HH Size_Average Household Size
59,Rangpur,Panchagarh,55,77,281627,1179843,280851,1176974,735,2827,...,56319,81106,53595,26636,11085,4651,2404,1281,1416,4.14
60,Rangpur,Rangpur,55,85,834307,3169614,826692,3141432,7447,28003,...,203689,231968,124275,52856,20364,8494,4142,2101,2248,3.72
61,Rangpur,Thakurgaon,55,94,382400,1533895,381262,1529809,1021,3930,...,82779,112589,66032,30798,11940,4898,2590,1297,1416,3.96
62,Sylhet,Sunamganj,60,90,528550,2695496,527545,2691484,865,3868,...,70460,104937,105541,78260,48226,27163,14596,8854,13911,5.09
63,Sylhet,Sylhet,60,91,746854,3857123,722553,3753617,23853,103032,...,102825,152780,143801,101254,62353,36293,21359,13723,24742,5.13

In [7]:
rows,cols=df.shape
print(f"Dataset Dimensions: {rows} rows * {cols} columns")

Dataset Dimensions: 64 rows * 445 columns

 Dataset Summary

Rows:     65 (64 administrative districts + 1 national aggregate)
Columns:  445 (housing metrics, population counts, and demographic indicators)
Format :  Wide-tabular datas

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 64 entries, 0 to 63
Columns: 445 entries, Division to Number of Person & Avg HH Size_Average Household Size
dtypes: float64(208), int64(234), str(3)
memory usage: 223.9 KB

In [9]:
df.describe()

,Division_Geocode,District_Geocode,Household_Total,Population_Total,Household_Excluding_Slum_Floating,Population_Excluding_Slum_Floating,Household_Slum,Population_Slum,Household_Floating,Population_Floating,...,Number of Person & Avg HH Size_# of HH with 3-Person,Number of Person & Avg HH Size_# of HH with 4-Person,Number of Person & Avg HH Size_# of HH with 5-Person,Number of Person & Avg HH Size_# of HH with 6-Person,Number of Person & Avg HH Size_# of HH with 7-Person,Number of Person & Avg HH Size_# of HH with 8-Person,Number of Person & Avg HH Size_# of HH with 9-Person,Number of Person & Avg HH Size_# of HH with 10-Person,Number of Person & Avg HH Size_# of HH with 10-Person +,Number of Person & Avg HH Size_Average Household Size
count,64.000000,64.000000,6.400000e+01,6.400000e+01,6.400000e+01,6.400000e+01,64.000000,64.000000,64.000000,64.000000,...,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000,64.000000
mean,36.406250,51.718750,6.407534e+05,2.580603e+06,6.327701e+05,2.553127e+06,7684.296875,27129.718750,298.968750,346.640625,...,140580.968750,163438.796875,104034.093750,51471.812500,23050.875000,10938.828125,5659.546875,3156.812500,4164.250000,4.031406
std,15.209353,27.003509,5.635301e+05,2.134836e+06,5.382841e+05,2.052937e+06,27837.256493,93746.357796,770.804115,853.589477,...,127738.850564,136359.196436,78102.420883,37512.175318,18268.022438,9525.834931,5253.640271,3221.510298,5208.502728,0.355335
min,10.000000,1.000000,1.061550e+05,4.811060e+05,1.060650e+05,4.810160e+05,0.000000,0.000000,0.000000,0.000000,...,19346.000000,24439.000000,19101.000000,11631.000000,4149.000000,1557.000000,688.000000,342.000000,252.000000,3.290000
25%,20.000000,31.500000,3.381995e+05,1.395069e+06,3.357908e+05,1.387069e+06,317.750000,1201.500000,69.250000,88.250000,...,72684.500000,92999.750000,61767.750000,29641.250000,12291.750000,5211.750000,2527.250000,1278.500000,1406.750000,3.805000
50%,40.000000,53.000000,5.225860e+05,2.156286e+06,5.212175e+05,2.148722e+06,1461.000000,5622.000000,127.500000,150.000000,...,102796.500000,134460.000000,92195.000000,43650.000000,17348.000000,8212.500000,3894.000000,1940.500000,2267.000000,3.985000
75%,50.000000,75.250000,7.503785e+05,2.955293e+06,7.452630e+05,2.935862e+06,3130.000000,12305.750000,275.750000,302.250000,...,165187.250000,184179.750000,123470.750000,58406.250000,26124.250000,11893.750000,6062.500000,3244.750000,3958.750000,4.150000
max,60.000000,94.000000,4.035241e+06,1.473470e+07,3.822371e+06,1.404069e+07,206900.000000,687534.000000,5970.000000,6477.000000,...,914430.000000,969773.000000,504971.000000,211944.000000,89097.000000,44943.000000,24934.000000,15625.000000,25295.000000,5.130000

## Unique values across all columns.

In [10]:
print(df.nunique(dropna=False).head(10))

Division                               8
District                              64
Division_Geocode                       8
District_Geocode                      64
Household_Total                       64
Population_Total                      64
Household_Excluding_Slum_Floating     64
Population_Excluding_Slum_Floating    64
Household_Slum                        63
Population_Slum                       63
dtype: int64

In [11]:
print(df.nunique(dropna=False).tail(10))

Number of Person & Avg HH Size_# of HH with 3-Person       64
Number of Person & Avg HH Size_# of HH with 4-Person       64
Number of Person & Avg HH Size_# of HH with 5-Person       64
Number of Person & Avg HH Size_# of HH with 6-Person       64
Number of Person & Avg HH Size_# of HH with 7-Person       64
Number of Person & Avg HH Size_# of HH with 8-Person       64
Number of Person & Avg HH Size_# of HH with 9-Person       64
Number of Person & Avg HH Size_# of HH with 10-Person      64
Number of Person & Avg HH Size_# of HH with 10-Person +    63
Number of Person & Avg HH Size_Average Household Size      51
dtype: int64

## Checking for inconsistencies in the dataset.

## Counting text columns

In [12]:
text_columns = df.select_dtypes(include=["object", "str"]).columns

print("Number of text columns:", len(text_columns))

Number of text columns: 3

## Lengths of the Columns and Their Data Types

In [13]:
for column in text_columns:
    print(f"\n--- {column} ---")
    print(df[column].unique())

--- Division ---
<ArrowStringArray>
[  'Barishal',     'Khulna', 'Chattogram',   'Rajshahi',      'Dhaka',
    'Rangpur',     'Sylhet', 'Mymensingh']
Length: 8, dtype: str

--- District ---
<ArrowStringArray>
[        'Barguna',        'Bagerhat',        'Barishal',           'Bhola',
       'Jhalokati',       'Bandarban',      'Patuakhali',        'Pirojpur',
    'Brahmanbaria',        'Chandpur',          'Bogura',      'Chattogram',
         'Cumilla',     'Cox's Bazar',            'Feni',    'Khagrachhari',
      'Lakshmipur',       'Chuadanga',        'Noakhali',       'Rangamati',
           'Dhaka',        'Faridpur',         'Gazipur',       'Gopalganj',
     'Kishoreganj',       'Madaripur',        'Dinajpur',       'Manikganj',
      'Munshiganj', 'Chapainababganj',     'Narayanganj',       'Narsingdi',
         'Rajbari',      'Shariatpur',       'Gaibandha',         'Tangail',
         'Jashore',       'Jhenaidah',        'Habiganj',          'Khulna',
         'Kushtia',        'Jamalpur',          'Magura',        'Meherpur',
          'Narail',        'Satkhira',      'Mymensingh',       'Joypurhat',
       'Netrakona',         'Sherpur',         'Naogaon',          'Natore',
        'Kurigram',           'Pabna',        'Rajshahi',     'Lalmonirhat',
       'Sirajganj',     'Moulvibazar',      'Nilphamari',      'Panchagarh',
         'Rangpur',      'Thakurgaon',       'Sunamganj',          'Sylhet']
Length: 64, dtype: str

--- Household by Roof Material_Wood/Bamboo/Bichali/Golpata Palm Leaf/Polythen ---
<ArrowStringArray>
[ '1.38',  '3.78',  '1.85',  '0.87',  '1.78', '14.83',  '1.07',  '2.35',
  '0.28',  '0.66',   '0.3',  '1.81',  '0.97', '15.01',  '4.76',   '0.5',
  '0.76',   '1.6',  '9.75',  '0.43',  '0.42',  '0.26',  '0.47',   '0.6',
  '0.46',  '1.23',     's',  '0.51',  '0.68',  '0.95',  '0.83',  '0.65',
  '4.65',  '0.35',  '0.63',  '0.77',  '0.99',  '3.91',   '0.8',  '0.53',
  '1.36',  '0.57',  '0.45',  '0.29',  '0.67',  '0.36',  '0.91',  '0.19',
  '1.47',  '0.75',  '1.01',  '0.98',  '1.74',  '2.15']
Length: 54, dtype: str

 ### Values that cannot be converted to numbers

In [14]:
column = "Household by Roof Material_Wood/Bamboo/Bichali/Golpata Palm Leaf/Polythen"


non_numeric = pd.to_numeric(df[column], errors="coerce").isna()

print(df.loc[non_numeric, column])

30    s
Name: Household by Roof Material_Wood/Bamboo/Bichali/Golpata Palm Leaf/Polythen, dtype: str

In [15]:
print(df.loc[non_numeric, ["Division", "District", column]])

   Division     District  \
30    Dhaka  Narayanganj

   Household by Roof Material_Wood/Bamboo/Bichali/Golpata Palm Leaf/Polythen
30                                                  s

In [16]:
print(df.loc[27:33, ["Division", "District", column]])

    Division         District  \
27     Dhaka        Manikganj
28     Dhaka       Munshiganj
29  Rajshahi  Chapainababganj
30     Dhaka      Narayanganj
31     Dhaka        Narsingdi
32     Dhaka          Rajbari
33     Dhaka       Shariatpur

   Household by Roof Material_Wood/Bamboo/Bichali/Golpata Palm Leaf/Polythen
27                                               0.26
28                                               1.23
29                                               0.43
30                                                  s
31                                               0.51
32                                               0.68
33                                               0.95

Non-Numeric String Error: Narayanganj District

## Figuring out the total number of numeric columns

In [17]:

numeric_columns = df.select_dtypes(include=["number"]).columns

print("Number of numeric columns:", len(numeric_columns))

print(df[numeric_columns].describe().T)

Number of numeric columns: 442
                                                    count          mean  \
Division_Geocode                                     64.0  3.640625e+01
District_Geocode                                     64.0  5.171875e+01
Household_Total                                      64.0  6.407534e+05
Population_Total                                     64.0  2.580603e+06
Household_Excluding_Slum_Floating                    64.0  6.327701e+05
...                                                   ...           ...
Number of Person & Avg HH Size_# of HH with 8-P...   64.0  1.093883e+04
Number of Person & Avg HH Size_# of HH with 9-P...   64.0  5.659547e+03
Number of Person & Avg HH Size_# of HH with 10-...   64.0  3.156812e+03
Number of Person & Avg HH Size_# of HH with 10-...   64.0  4.164250e+03
Number of Person & Avg HH Size_Average Househol...   64.0  4.031406e+00

                                                             std        min  \
Division_Geocode                                    1.520935e+01      10.00
District_Geocode                                    2.700351e+01       1.00
Household_Total                                     5.635301e+05  106155.00
Population_Total                                    2.134836e+06  481106.00
Household_Excluding_Slum_Floating                   5.382841e+05  106065.00
...                                                          ...        ...
Number of Person & Avg HH Size_# of HH with 8-P...  9.525835e+03    1557.00
Number of Person & Avg HH Size_# of HH with 9-P...  5.253640e+03     688.00
Number of Person & Avg HH Size_# of HH with 10-...  3.221510e+03     342.00
Number of Person & Avg HH Size_# of HH with 10-...  5.208503e+03     252.00
Number of Person & Avg HH Size_Average Househol...  3.553352e-01       3.29

                                                            25%          50%  \
Division_Geocode                                         20.000       40.000
District_Geocode                                         31.500       53.000
Household_Total                                      338199.500   522586.000
Population_Total                                    1395068.750  2156285.500
Household_Excluding_Slum_Floating                    335790.750   521217.500
...                                                         ...          ...
Number of Person & Avg HH Size_# of HH with 8-P...     5211.750     8212.500
Number of Person & Avg HH Size_# of HH with 9-P...     2527.250     3894.000
Number of Person & Avg HH Size_# of HH with 10-...     1278.500     1940.500
Number of Person & Avg HH Size_# of HH with 10-...     1406.750     2267.000
Number of Person & Avg HH Size_Average Househol...        3.805        3.985

                                                           75%          max
Division_Geocode                                         50.00        60.00
District_Geocode                                         75.25        94.00
Household_Total                                      750378.50   4035241.00
Population_Total                                    2955292.75  14734701.00
Household_Excluding_Slum_Floating                    745263.00   3822371.00
...                                                        ...          ...
Number of Person & Avg HH Size_# of HH with 8-P...    11893.75     44943.00
Number of Person & Avg HH Size_# of HH with 9-P...     6062.50     24934.00
Number of Person & Avg HH Size_# of HH with 10-...     3244.75     15625.00
Number of Person & Avg HH Size_# of HH with 10-...     3958.75     25295.00
Number of Person & Avg HH Size_Average Househol...        4.15         5.13

[442 rows x 8 columns]

## Checking if there are any negative values.

In [18]:

numeric_columns = df.select_dtypes(include=["number"]).columns

negative_values = (df[numeric_columns] < 0).sum()

print(negative_values[negative_values > 0])

Population Growth Rate, Sex Rat_Overall_Avg_Population Growth     1
Population Growth Rate, Sex Rat_Rural_Avg. Population Growth     25
Population Growth Rate, Sex Rat_Urban_Avg__Population Growth      1
dtype: int64

## Checking if there are any infinite values.

In [19]:

infinite_values = np.isinf(df[numeric_columns]).sum()

print(infinite_values[infinite_values > 0])

Series([], dtype: int64)

## Checking column with percentage and their validity

In [20]:
percentage_columns = [ column for column in df.columns if "%" in column or "percent" in column.lower() or "percentage" in column.lower()] 

print("Number of percentage columns:", len(percentage_columns))

for column in percentage_columns:
 print(column)

Number of percentage columns: 158
Type of Household, Dist and Loca_% Population_General HH
Type of Household, Dist and Loca_% Population_Institutional HH
Type of Household, Dist and Loca_% Population_other HH
Type of Household, Loca_Rural_% Population_General HH_Rural
Type of Household, Loca_Rural_% Population_Institutional HH_Rural
Type of Household, Loca_Rural_% Population_other HH_Rural
Type of Household, Loca_Urban.% Population_General HH_Urban
Type of Household, Loca_Urban.% Population_Institutional HH_Urban
Type of Household, Loca_Urban.% Population_other HH_Urban
15-24 Years NEET_%_Overall
15-24 Years NEET_%_male_Overall
15-24 Years NEET_%_female_Overall
15-24 Years NEET_%_rural_Overall
15-24 Years NEET_%_male_rural_Overall
15-24 Years NEET_%_female_rural_Overall
15-24 Years NEET_%_urban_Overall
15-24 Years NEET_%_male_urban_Overall
15-24 Years NEET_%_female_urban_Overall
15-24 Years NEET_%_15_19 year_overall
15-24 Years NEET_%_male_15_19 year
15-24 Years NEET_%_female_15_19 year
15-24 Years NEET_%_rural_15_19 year
15-24 Years NEET_%_male_rural_15_19 year
15-24 Years NEET_%_female_rural_15_19 year
15-24 Years NEET_%_urban_15_19 year
15-24 Years NEET_%_male_urban_15_19 year
15-24 Years NEET_%_female_urban_15_19 year
15-24 Years NEET_%_20_24 year_overall
15-24 Years NEET_%_male_20_24 year
15-24 Years NEET_%_female_20_24 year
15-24 Years NEET_%_rural_20_24 year
15-24 Years NEET_%_male_rural_20_24 year
15-24 Years NEET_%_female_rural_20_24 year
15-24 Years NEET_%_urban_20_24 year
15-24 Years NEET_%_male_urban_20_24 year
15-24 Years NEET_%_female_urban_20_24 year
%_Mobile Phone_Total_5year+
%_Mobile Phone_Male_5year+
%_Mobile Phone_Female_5year+
%_Mobile Phone_Rural_Total_5year+
%_Mobile Phone_Rural_Male_5year+
%_Mobile Phone_Rural_female_5year+
%_Mobile Phone_urban_Total_5year+
%_Mobile Phone_urban_Male_5year+
%_Mobile Phone_urban_female_5year+
%_Mobile Phone_Total_15 year+
%_Mobile Phone_Male_15 year+
%_Mobile Phone_Female_15 year+
%_Mobile Phone_Rural_Total_15 year+
%_Mobile Phone_Rural_Male_15 year+
%_Mobile Phone_Rural_female_15 year+
%_Mobile Phone_urban_Total_15 year+
%_Mobile Phone_urban_Male_15 year+
%_Mobile Phone_urban_female_15 year+
%_Inernet_Total_5year+
%_Inernet_Male_5year+
%_Inernet_Female_5year+
%_Inernet_Rural_Total_5year+
%_Inernet_Rural_Male_5year+
%_Inernet_Rural_female_5year+
%_Inernet_urban_Total_5year+
%_Inernet_urban_Male_5year+
%_Inernet_urban_female_5year+
%_Inernet_Total_15 year+
%_Inernet_Male_15 year+
%_Inernet_Female_15 year+
%_Inernet_Rural_Total_15 year+
%_Inernet_Rural_Male_15 year+
%_Inernet_Rural_female_15 year+
%_Inernet_urban_Total_15 year+
%_Inernet_urban_Male_15 year+
%_Inernet_urban_female_15 year+
%_Have financial account_Overall
%_Have financial account_Male
%_Have financial account_Female
%_Have financial account_Rural
%_Have financial account_Rural_Male
%_Have financial account_Rural_Female
%_Have financial account_Urban
%_Have financial account_Urban_Male
%_Have financial account_Urban_Female
%_Mobile Bank Account_Overall
%_Mobile Bank Account_Male
%_Mobile Bank Account_Female
%_Mobile Bank Account_Rural
%_Mobile Bank Account_Rural_Male
%_Mobile Bank Account_Rural_Female
%_Mobile Bank Account_Urban
%_Mobile Bank Account_Urban_Male
%_Mobile Bank Account_Urban_Female
% Male_Ethnic Population
% Female_Ethnic Population
% Overall_Bangladeshi_National
% Male_Bangladeshi_National
% Female_Bangladeshi_National
% Hizra_Bangladeshi_National
Percent_Returned_Migrant
Household by Wall Material_Cement/Concrete/Brick/Terracotta_Wall_%
Household by Wall Material_Ceramic Tiles_Wall_%
Household by Wall Material_Soil/ Mud_Wall_%
Household by Wall Material_Other Materials__Wall_%
Household by Wall Material_No wall %
Household by Roof Material_Cement/Concrete/Tile_roof_%
Household by Roof Material_Hand-made Tiles/Tile_roof_%
Household by Roof Material_Other Materials_roof_%
Household by Roof Material_No_roof_%
Household by Floor Material_Cement/Concrete/Brick/Terracotta_floor_%
Household by Floor Material_Tiles/Mosaic_floor_%
Household by Floor Material_Soil/Sand/Mud_floor_%
Household by Floor Material_Other Materials_floor_%
Household by Structure_Total_%
Household by Structure_Pucca_%
Household by Structure_Semi-pucca_%
Household by Structure_Kancha_%
Household by Structure_Jhupri_%
Household by Ownership Status_Own dwelling unit_%
Household by Ownership Status_Rented but having own dwelling unit elsewhere_%
Household by Ownership Status_Rented and having no own dwelling unit_%
Household by Ownership Status_Rent free but having own dwelling unit elsewhere_%
Household by Ownership Status_Rent free and having no own dwelling unit elsewhere_%
Main Source of Drinking Water_Tap/pipe (Supply)_%
Main Source of Drinking Water_Tube-well (Deep/Shallow)_%
Main Source of Drinking Water_Bottled/Jar Water_%
Main Source of Drinking Water_Well_%
Main Source of Drinking Water_Pond/River/Canal/Lake_%
Main Source of Drinking Water_Spring_%
Main Source of Drinking Water_Rain Water_%
Main Source of Drinking Water_Others_%
Toilet Facilities_Safe Disposal with Flushing/ Pouring Water_%
Toilet Facilities_Safe Disposal with Flushing/ Pouring Water_%2
Toilet Facilities_Safe Disposal with Flushing/ Pouring Water_%3
Toilet Facilities_Pit Latrine
Without
Slab/ Open_%
Pit
Toilet Facilities_Raw/Open/ Hanging Latrine (Permanent/ Temporary)_%
Toilet Facilities_Open Defecation/ No Latrine Available_%
Type of Toilet Use_Toilet_Not-Toilet_Shared_%
Type of Toilet Use_Toilet_Shared_%
Type of Toilet Use_Rural_Toilet_Not-Toilet_Shared_%
Type of Toilet Use_Rural_Toilet_Shared_%
Type of Toilet Use_urban_Toilet_Not-Toilet_Shared_%
Type of Toilet Use_urban_Toilet_Shared_%
Handwashing Facilities_Soap & Water_%
Handwashing Facilities_Only Soap_%
Handwashing Facilities_Only Water_%
Handwashing Facilities_No Separate Arrangement_%
Main Source of Electricity_National Grid_%
Main Source of Electricity_Solar Power_%
Main Source of Electricity_Others_%
Main Source of Electricity_No Electricity Connection_%
Main Source of Cooking Fuel_Straw/ Leaf/ Bran/ Husk_%
Main Source of Cooking Fuel_Wood/ Chalk/ Chopped Wood_%
Main Source of Cooking Fuel_Wood-coal/ Charcoal/ Dried Dung_%
Main Source of Cooking Fuel_Kerosene/ Paraffin_%
Main Source of Cooking Fuel_Petrol/ Diesel_%
Main Source of Cooking Fuel_Electricty_%
Main Source of Cooking Fuel_Supply Gas_%
Main Source of Cooking Fuel_ LP Gas_%
Main Source of Cooking Fuel_Biogas_%
Main Source of Cooking Fuel_Others_%

In [21]:
invalid_percentage_columns = []

for column in percentage_columns:
    invalid = df[(df[column] < 0) | (df[column] > 100)]

    if not invalid.empty:
        invalid_percentage_columns.append(column)
        print(f"\nInvalid values in: {column}")
        print(invalid[["Division", "District", column]])

if not invalid_percentage_columns:
    print("All percentage columns contain valid values between 0% and 100%.")

All percentage columns contain valid values between 0% and 100%.

Here are 158 columns with percentages that contain valid values between 0% and 100%."